burvey-app/src/main/java/lt/bleizitsoft/burvey/usecase/createsurveymodule/CreateSurveyController.java
package lt.bleizitsoft.burvey.usecase.createsurveymodule;

import lombok.Getter;
import lombok.Setter;
import lt.bleizitsoft.burvey.api.authCheck.LoggedIn;
import lt.bleizitsoft.burvey.api.authentification.IAuthenticatedUserHolder;
import lt.bleizitsoft.burvey.api.dao.ISurveyDAO;
import lt.bleizitsoft.burvey.api.staticobjects.InfoMessages;
import lt.bleizitsoft.burvey.api.staticobjects.PagePaths;
import lt.bleizitsoft.burvey.api.staticobjects.SurveyQuestionType;
import lt.bleizitsoft.burvey.api.utils.UrlParser;
import lt.bleizitsoft.burvey.entities.*;
import lt.bleizitsoft.burvey.api.log.LogBusinessLogicInterceptorBinding;
import org.omnifaces.util.Faces;
import org.primefaces.context.RequestContext;

import javax.annotation.PostConstruct;
import javax.faces.context.FacesContext;
import javax.faces.view.ViewScoped;
import javax.inject.Inject;
import javax.inject.Named;
import javax.servlet.http.HttpServletRequest;
import javax.transaction.Transactional;
import java.io.IOException;
import java.io.Serializable;
import java.time.Duration;
import java.util.*;

/**
 * Created by Gintautas.Grisius on 2017-05-18.
 */
@LoggedIn
@Named
@ViewScoped
public class CreateSurveyController implements Serializable {

    private enum CURRENT_ACTION {
        INFO, QUESTIONS, CONFIRMATION, DONE
    }

    @Inject
    private ISurveyDAO surveyDAO;

    @Inject
    private HttpServletRequest httpServletRequest;

    @Inject
    private IAuthenticatedUserHolder authenticatedUserHolder;

    @Getter @Setter
    private Survey survey = new Survey();

    @Getter
    private String questionType;

    @Getter @Setter
    private Question question = new Question();

    @Getter @Setter
    private NumberQuestion numberQuestion = new NumberQuestion();

    @Getter @Setter
    private ArrayList<AnswerOption> answerOptions = new ArrayList<AnswerOption>();

    @Getter
    private Map<String, String> displayStyle = new HashMap<String, String>();

    @Getter @Setter
    private Object dummyAnswer;

    @Getter
    private boolean updatingExisting = false;

    @Getter
    private boolean isEditable = true;

    private CURRENT_ACTION currentAction = CURRENT_ACTION.INFO;
    public boolean isCurrentAction(CURRENT_ACTION action) {
        return currentAction == action;
    }

    @PostConstruct
    private void init() {

        displayStyle.put("step1", "selected");
        displayStyle.put("step2", "disabled");
        displayStyle.put("step3", "disabled");

        List<String> queryParams = UrlParser.getBaseUrl(httpServletRequest);
        if(queryParams.size() >= 2 && queryParams.get(0).equals("access_link")) {
            survey = surveyDAO.readByColumnAccessLink(queryParams.get(1)).orElse(null);
            if (survey == null || (!authenticatedUserHolder.isAdministrator() &&
                    survey.getOwner().getId() != authenticatedUserHolder.getAuthenticatedUserProfile().getId())) {
                try {
                    InfoMessages.setErrorMessage("Tokia apklausa neegzistuoja!");

                    FacesContext.getCurrentInstance().getExternalContext().getFlash().setKeepMessages(true);
                    Faces.redirect("index");
                } catch (IOException e) {

                }
            }
            checkSurveyEditable();
            updatingExisting = true;
            return;
        }
        survey.setQuestionList(new ArrayList<>());
        survey.setOwner(authenticatedUserHolder.getAuthenticatedUserProfile());
        survey.setIsActive(true);
    }

    public void nextPage() {
        switch (currentAction) {
            case INFO:
                currentAction = CURRENT_ACTION.QUESTIONS;
                survey.setExpirationDate(addTimeFromUTC(survey.getExpirationDate()));
                displayStyle.put("step1", "done");
                displayStyle.put("step2", "selected");
                break;
            case QUESTIONS:
                currentAction = CURRENT_ACTION.CONFIRMATION;
                displayStyle.put("step2", "done");
                displayStyle.put("step3", "selected");
                break;
            case CONFIRMATION:
                break;
        }
    }

    public void previousPage() {
        switch (currentAction) {
            case INFO:
                break;
            case QUESTIONS:
                currentAction = CURRENT_ACTION.INFO;
                survey.setExpirationDate(setTimeToUTC(survey.getExpirationDate()));
                displayStyle.put("step1", "selected");
                displayStyle.put("step2", "done");
                break;
            case CONFIRMATION:
                currentAction = CURRENT_ACTION.QUESTIONS;
                displayStyle.put("step2", "selected");
                displayStyle.put("step3", "done");
                break;
        }
    }

    @LogBusinessLogicInterceptorBinding
    @Transactional
    public void saveSurvey() {
        if (survey.getQuestionList().size() == 0) {
            InfoMessages.setErrorMessage("Įveskite bent vieną klausimą!");
            return;
        }

        if (updatingExisting) {
            InfoMessages.setInfoMessage("Apklausa sėkmingai atnaujinta!");
            surveyDAO.update(survey);
            currentAction = CURRENT_ACTION.DONE;
            return;
        }

        survey.setQuestionsPerPage(5);
        survey.setActivationDate(new Date());
        survey.setAccessLink(UUID.randomUUID().toString());
        surveyDAO.create(survey);

        currentAction = CURRENT_ACTION.DONE;
        InfoMessages.setInfoMessage("Apklausa sėkmingai sukurta!");
    }

    public void addNewQuestion(int type) {
        question = new Question();
        changeQuestionType(type);
        question.setQuestionType(questionType);
        question.setSurvey(survey);
        question.setOrderNr(survey.getQuestionList().size()+1);

        if (questionType.equals(SurveyQuestionType.scale)) {
            numberQuestion = new NumberQuestion();
            numberQuestion.setQuestion(question);
        } else {
            answerOptions = new ArrayList<AnswerOption>();
            addAnswerOption();
            addAnswerOption();
        }
    }

    public void addAnswerOption() {
        answerOptions.add(createAnswerOption());
    }

    public void removeAnswerOption(int index) {
        answerOptions.remove(index);
    }

    public AnswerOption createAnswerOption() {
       AnswerOption answerOption = new AnswerOption();
       answerOption.setQuestion(question);

       return answerOption;
    }

    public void addQuestion() {
        switch (questionType) {
            case SurveyQuestionType.multipleChoice:
                question.setAnswerOptionList(answerOptions);
                break;
            case SurveyQuestionType.checkbox:
                question.setAnswerOptionList(answerOptions);
                break;
            case SurveyQuestionType.scale:
                if (numberQuestion.getMinimalRange() >= numberQuestion.getMaximumRange()) {
                    InfoMessages.setErrorMessage("Minimalus rėžis negali būti didesnis arba lygus maksimaliam!", "modalMessages");
                    return;
                }
                question.setNumberQuestion(numberQuestion);
                break;
        }
        survey.getQuestionList().add(question);
        question = new Question();
        RequestContext.getCurrentInstance().execute("$('.modalPseudoClass').hide();$('.modal-backdrop').remove(); " +
                "$('body').css('overflow', 'auto');");
    }

    public void changeQuestionType(int type) {
        switch (type) {
            case 1:
                questionType = SurveyQuestionType.multipleChoice;
                break;
            case 2:
                questionType = SurveyQuestionType.checkbox;
                break;
            case 3:
                questionType = SurveyQuestionType.text;
                break;
            case 4:
                questionType = SurveyQuestionType.scale;
                break;
        }
    }

    public void questionAction(String action, int currentIndex) {
        switch (action) {
            case "up":
                if (currentIndex < 1) return;
                survey.getQuestionList().get(currentIndex).setOrderNr(currentIndex);
                survey.getQuestionList().get(currentIndex-1).setOrderNr(currentIndex+1);
                Collections.swap(survey.getQuestionList(), currentIndex, currentIndex-1);
                break;
            case "down":
                if (currentIndex == survey.getQuestionList().size()-1) return;
                survey.getQuestionList().get(currentIndex).setOrderNr(currentIndex+2);
                survey.getQuestionList().get(currentIndex+1).setOrderNr(currentIndex+1);
                Collections.swap(survey.getQuestionList(), currentIndex, currentIndex+1);
                break;
            case "delete":
                survey.getQuestionList().remove(currentIndex);
                break;
        }

    }

    public String getSurveyAddress() {
        return PagePaths.BASE_PATH + PagePaths.ANSWER_SURVEY_LINK + "?access_link=" + survey.getAccessLink();
    }

    private void checkSurveyEditable() {
        for (Question question : survey.getQuestionList()) {
            if (question.getUserAnswerList().size() != 0)
            {
                isEditable = false;
                return;
            }
        }
    }

    //adds time from utc to current time zone (+2/+3)
    private Date addTimeFromUTC(Date currentDate) {
        return Date.from(currentDate.toInstant().plus(Duration.ofHours(getHourDiffBetweenUTC())));
    }

    private Date setTimeToUTC(Date currentDate) {
        return Date.from(currentDate.toInstant().minus(Duration.ofHours(getHourDiffBetweenUTC())));
    }

    private int getHourDiffBetweenUTC() {
        return 3;
        //TimeZone.getTimeZone("Europe/Vilnius").getOffset(Calendar.getInstance().getTimeInMillis());
    }
}

burvey-app/src/main/java/lt/bleizitsoft/burvey/usecase/surveyreportmodule/SurveyReportController.java
package lt.bleizitsoft.burvey.usecase.surveyreportmodule;

import lt.bleizitsoft.burvey.api.authCheck.LoggedIn;
import lt.bleizitsoft.burvey.api.staticobjects.PagePaths;
import lt.bleizitsoft.burvey.api.utils.UrlParser;
import lt.bleizitsoft.burvey.dao.sync.QuestionDAO;
import lt.bleizitsoft.burvey.dao.sync.SurveyDAO;
import lt.bleizitsoft.burvey.dao.sync.UserAnswerNumberDAO;
import lt.bleizitsoft.burvey.dao.sync.UserAnswerTextDAO;
import lt.bleizitsoft.burvey.entities.Question;
import lt.bleizitsoft.burvey.entities.Survey;
import lt.bleizitsoft.burvey.api.log.LogBusinessLogicInterceptorBinding;
import org.omnifaces.util.Faces;

import javax.annotation.PostConstruct;
import javax.enterprise.inject.Model;
import javax.faces.context.FacesContext;
import javax.inject.Inject;
import javax.servlet.http.HttpServletRequest;
import java.io.IOException;
import java.util.List;
import java.util.Optional;

/**
 * Created by Albe on 2017-05-25.
 */
@LoggedIn
@Model
public class SurveyReportController {

    private Survey survey;

    private int id;


    @Inject
    SurveyDAO surveyDAO;


    @Inject
    QuestionDAO questionDAO;

    @Inject
    UserAnswerNumberDAO userAnswerNumberDAO;

//    @Inject
//    UserAnswerOptionDAO userAnswerOptionDAO;

    @Inject
    UserAnswerTextDAO userAnswerTextDAO;

    @Inject
    private HttpServletRequest httpServletRequest;


    @PostConstruct
    public void initQuery() {
        String url = httpServletRequest.getRequestURL().toString();
        if (url.contains(PagePaths.BASE_PATH + PagePaths.REPORT_LINK)) {
            List<String> result = UrlParser.getBaseUrl(httpServletRequest);

            if (result != null && result.size()>=2) {
                String paramName = result.get(0);
                String paramVal = result.get(1);

                if (paramName.equals("access_link")) {
                    Optional<Survey> surveyOptional = surveyDAO.readByColumnAccessLink(paramVal);

                    if (surveyOptional.isPresent()) {
                        survey = surveyOptional.get();
                        id = survey.getId();

                    } else {
                        try {
                            FacesContext.getCurrentInstance().getExternalContext().getFlash().setKeepMessages(true);
                            Faces.redirect("index");
                        } catch (IOException e) {
                            e.printStackTrace();
                        }
                    }
                }
            } else {
                try {
                    FacesContext.getCurrentInstance().getExternalContext().getFlash().setKeepMessages(true);
                    Faces.redirect("index");
                } catch (IOException e) {
                    e.printStackTrace();
                }
            }
        }
    }


    @LogBusinessLogicInterceptorBinding
    public List<Question> getSurveyQuestions()
    {
        return questionDAO.readByColumnSurveyId(id);
    }

    @LogBusinessLogicInterceptorBinding
    public Integer getQuestionAnswersCount(Question question){
        return question.getUserAnswerList().size();
    }
}

burvey-app/src/main/java/lt/bleizitsoft/burvey/usecase/usercontrolmodule/UsersManagementController.java
package lt.bleizitsoft.burvey.usecase.usercontrolmodule;

import lombok.Getter;
import lombok.Setter;
import lt.bleizitsoft.burvey.EmailService.Emailer;
import lt.bleizitsoft.burvey.api.authCheck.AdministratorOnly;
import lt.bleizitsoft.burvey.api.dao.ICandidateInfoDAO;
import lt.bleizitsoft.burvey.api.dao.IUserProfileDAO;
import lt.bleizitsoft.burvey.api.emailService.ILinkEmailer;
import lt.bleizitsoft.burvey.api.staticobjects.InfoMessages;
import lt.bleizitsoft.burvey.entities.CandidateInfo;
import lt.bleizitsoft.burvey.entities.UserProfile;
import lt.bleizitsoft.burvey.api.log.LogBusinessLogicInterceptorBinding;

import javax.enterprise.inject.Model;
import javax.inject.Inject;
import javax.transaction.Transactional;
import java.util.List;

@Model
@AdministratorOnly
public class UsersManagementController {

    @Inject
    private IUserProfileDAO userProfileDAO;

    @Inject
    private ICandidateInfoDAO candidateInfoDAO;

    @Inject
    private ILinkEmailer emailer;

    @Getter @Setter
    private String email;

    public List<CandidateInfo> getAllUsers() { return candidateInfoDAO.readAll(); }

    @LogBusinessLogicInterceptorBinding
    @Transactional
    public void blockUser (int userId){
        UserProfile user = userProfileDAO.readById(userId).orElse(null);
        if (user == null) {
            return;
        }
        user.setBlocked(true);
        userProfileDAO.update(user);
    }

    @LogBusinessLogicInterceptorBinding
    @Transactional
    public void unblockUser (int userId){
        UserProfile user = userProfileDAO.readById(userId).orElse(null);
        if (user == null) {
            return;
        }
        user.setBlocked(false);
        userProfileDAO.update(user);
    }

    @LogBusinessLogicInterceptorBinding
    @Transactional
    public void makeAdmin (int userId){
        UserProfile user = userProfileDAO.readById(userId).orElse(null);
        if (user == null) {
            return;
        }
        user.setAdministrator(true);
        userProfileDAO.update(user);
    }

    @LogBusinessLogicInterceptorBinding
    @Transactional
    public void removeAdmin (int userId){
        UserProfile user = userProfileDAO.readById(userId).orElse(null);
        if (user == null) {
            return;
        }
        user.setAdministrator(false);
        userProfileDAO.update(user);
    }

    @LogBusinessLogicInterceptorBinding
    @Transactional
    public void removeCandidate(int userId) {
        candidateInfoDAO.delete(candidateInfoDAO.readById(userId).get());
        InfoMessages.setInfoMessage("Naudotojas pašalintas!");
    }

    @LogBusinessLogicInterceptorBinding
    @Transactional
    public void addNewUser() {

        if (!emailer.isValidEmailAddress(email)) {
            InfoMessages.setErrorMessage("Įvestas klaidingas el. pašto adresas!");
            return;
        }

        if (candidateInfoDAO.readByColumnEmailAddress(email).isPresent()) {
            InfoMessages.setErrorMessage("Naudotojas su tokiu el. paštu jau egzistuoja!");
            return;
        }

        CandidateInfo candidateInfo = new CandidateInfo();
        candidateInfo.setEmailAddress(email);
        candidateInfoDAO.create(candidateInfo);
        InfoMessages.setInfoMessage("Naudotojas pridėtas!");
    }

}

burvey-app/src/main/webapp/WEB-INF/faces-views/forgot_password.xhtml
<ui:composition template="../../template/login_template.xhtml"
                xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                xmlns:b="http://bootsfaces.net/ui">
    <ui:define name="title">Pamiršote slaptažodį</ui:define>
    <ui:define name="content">
        <h:panelGroup layout="block" styleClass="login_wrapper" id="loginForm">
                    <div id="register" class="animate form login_form">
                        <section class="login_content">
                            <h:form>
                                <b:messages id="messages" />
                                <h1>Pamiršote slaptažodį</h1>
                                <div style="padding-bottom: 20px;">
                                    Įveskite savo el. pašto adresą, į kurį gausite slaptažodžio atkūrimo nuorodą.
                                </div>
                                <div>
                                    <b:inputText value="#{passwordRecoveryRequestController.email}" type="email" styleClass="form-control" placeholder="Pašto adresas" required="true" requiredMessage="Neįrašėte pašto"/>
                                </div>
                                <div>
                                    <b:commandButton styleClass="btn btn-default" value="Siųsti" action="#{passwordRecoveryRequestController.requestPassRecovery}"/>
                                </div>

                                <div class="clearfix"></div>
                            </h:form>
                                <div class="separator">
                                    <p class="change_link">
                                        <h:outputLink value="login"><b>Grįžti į prisijungimo puslapį</b></h:outputLink>
                                    </p>
                                </div>
                        </section>
            </div>
        </h:panelGroup>
    </ui:define>
</ui:composition>

burvey-app/src/main/webapp/WEB-INF/faces-views/login.xhtml
<ui:composition template="../../template/login_template.xhtml"
                xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                xmlns:b="http://bootsfaces.net/ui">
  <ui:define name="title">Prisijungimas</ui:define>
  <ui:define name="content">
    <div>
      <a class="hiddenanchor" id="signup"></a>
      <a class="hiddenanchor" id="signin"></a>
      <h:panelGroup layout="block" styleClass="login_wrapper" id="loginForm">
        <div class="animate form login_form">
          <section class="login_content">
            <h:form>
              <b:messages id="messages" />
              <h1>Prisijungimas</h1>
              <div>
                <b:inputText value="#{authenticatorUseCaseController.userEmailAddress}" type="text" styleClass="form-control" placeholder="El. paštas"/>
              </div>
              <div>
                <b:inputText value="#{authenticatorUseCaseController.userPassword}" type="password" styleClass="form-control" placeholder="Slaptažodis"/>
              </div>
              <div  style="padding-bottom: 20px;">
                <b:commandButton styleClass="btn btn-default" value="Prisijungti" action="#{authenticatorUseCaseController.loginAndRedirect}"/>
              </div>
                <h:outputLink value="forgot_password"><b>Priminti slaptažodį</b></h:outputLink>

              <p class="change_link">Nesate užsiregistravęs?
                <a href="#signup" class="to_register"> <b>Registracija</b> </a>
              </p>
              <div class="clearfix"></div>

              <div class="separator">
                <div>
                  <p>Gentelella by ColorLib</p>
                </div>
              </div>
            </h:form>
          </section>
        </div>

        <div id="register" class="animate form registration_form">
          <section class="login_content">
            <h:form>
              <h1>Registracija</h1>
              <div>
                <b:inputText value="#{registryController.email}" type="email" styleClass="form-control" placeholder="Pašto adresas" required="true" requiredMessage="Neįrašėte pašto"/>
              </div>
              <div>
                <b:commandButton styleClass="btn btn-default" value="Registruotis" action="#{registryController.requestRegister()}"/>
              </div>

              <div class="clearfix"></div>

              <div class="separator">
                <p class="change_link">Jau narys?
                  <a href="#signin" class="to_register"> <b>Prisijunk</b> </a>
                </p>

                <div class="clearfix"></div>
                <br />

                <div>
                  <p>Gentelella by ColorLib</p>
                </div>
              </div>
            </h:form>
          </section>
        </div>
      </h:panelGroup>
    </div>
  </ui:define>
</ui:composition>

burvey-app/src/main/webapp/WEB-INF/faces-views/users_management.xhtml
<ui:composition template="../../template/common_template.xhtml"
                xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                xmlns:b="http://bootsfaces.net/ui"
                xmlns:f="http://xmlns.jcp.org/jsf/core">
    <ui:define name="title">Vartotojų valdymas</ui:define>
    <ui:define name="content">
        <div class="right_col" role="main" id="main">
          <h:panelGroup layout="block" id="usersPage">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                    <div class="title_left">
                        <h3>Naudotojų sąrašas</h3>
                    </div>
                    <h:panelGroup layout="block" styleClass="x_content" id="x_content">
                        <b:messages id="messages" />
                        <b:dataTable value="#{usersManagementController.allUsers}" var="user"
                                     id="datatable-responsive"
                                     styleClass="table table-striped table-bordered dt-responsive nowrap"
                                     style="overflow: hidden !important;"
                                     scrollable="false"
                                     widgetVar="dataTableWidgetVar"
                                     customLangUrl="http://cdn.datatables.net/plug-ins/1.10.13/i18n/Lithuanian.json"
                                     cellspacing="0"
                                     width="100%">
                            <h:column>
                                <f:facet name="header">El. paštas</f:facet>
                                #{user.emailAddress}
                            </h:column>
                            <h:column>
                                <f:facet name="header">Vardas</f:facet>
                                #{user.userProfile.name} #{user.userProfile.surname}
                            </h:column>
                            <h:column>
                                <f:facet name="header">Aktyvacijos data</f:facet>
                                <h:outputText value="#{user.activationDate}" >
                                    <f:convertDateTime pattern="yyyy-MM-dd HH:mm" />
                                </h:outputText>
                            </h:column>
                            <h:column>
                                <f:facet name="header">Administratorius</f:facet>
                                <h:outputText value="Taip" style="color:green;font-weight:bold;" rendered="#{user.userProfile.administrator}" />
                                <h:outputText value="Ne" rendered="#{!user.userProfile.administrator and user.userProfile ne null}" />
                            </h:column>
                            <h:column>
                                <f:facet name="header">Blokuotas</f:facet>
                                <h:outputText value="Taip" style="color:red;font-weight:bold;"  rendered="#{user.userProfile.blocked}" />
                                <h:outputText value="Ne" rendered="#{!user.userProfile.blocked and user.userProfile ne null}" />
                            </h:column>
                            <h:column>
                                <f:facet name="header">Veiksmai</f:facet>
                               <h:form>
                                <h:panelGroup layout="block" rendered="#{user.userProfile ne null}">
                                        <b:commandButton value="Užblokuoti"
                                                         actionListener="#{usersManagementController.blockUser(user.id)}"
                                                         update=":datatable-responsive  :messages"
                                                         size="xs"
                                                         look="primary"
                                                         oncomplete="dataTableWidgetVar.filter()"
                                                         disabled="#{(user.userProfile.id eq authenticatedUserHolder.authenticatedUserProfile.id)}"
                                                         rendered="#{!user.userProfile.blocked}"
                                        />

                                        <b:commandButton value="Atblokuoti"
                                                         actionListener="#{usersManagementController.unblockUser(user.id)}"
                                                         update=":datatable-responsive  :messages"
                                                         size="xs"
                                                         look="info"
                                                         oncomplete="dataTableWidgetVar.filter()"
                                                         rendered="#{user.userProfile.blocked and (user.userProfile.id ne authenticatedUserHolder.authenticatedUserProfile.id)}"
                                        />

                                        <b:commandButton value="Panaikinti administratoriaus teises"
                                                         actionListener="#{usersManagementController.removeAdmin(user.id)}"
                                                         update=":datatable-responsive  :messages"
                                                         size="xs"
                                                         look="warning"
                                                         oncomplete="dataTableWidgetVar.filter()"
                                                         rendered="#{user.userProfile.administrator}"
                                        />

                                        <b:commandButton value="Padaryti administratoriumi"
                                                         actionListener="#{usersManagementController.makeAdmin(user.id)}"
                                                         update=":datatable-responsive  :messages"
                                                         size="xs"
                                                         look="success"
                                                         oncomplete="dataTableWidgetVar.filter()"
                                                         rendered="#{!user.userProfile.administrator}"
                                        />
                                </h:panelGroup>
                                    <b:commandButton value="Pašalinti"
                                                     actionListener="#{usersManagementController.removeCandidate(user.id)}"
                                                     update=":datatable-responsive :messages"
                                                     size="xs"
                                                     look="danger"
                                                     oncomplete="dataTableWidgetVar.filter()"
                                                     rendered="#{user.userProfile eq null}"
                                    />
                                </h:form>
                            </h:column>
                        </b:dataTable>
                    </h:panelGroup>
                </div>
            </div>

            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                    <div class="title_left">
                        <h4>Pridėti naudotoją</h4>
                    </div>
                    <div class="x_content">
                        <b:form id="form">
                            <h:panelGroup layout="block" class="form-horizontal form-label-left form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12">
                                    Elektroninio pašto adresas:
                                    <span class="required">*</span>
                                </label>
                                <h:panelGroup layout="block" class="col-md-6 col-sm-6 col-xs-12">
                                    <b:inputText value="#{usersManagementController.email}"
                                                 required="true"
                                                 class="form-control col-md-4 col-xs-12"
                                                 requiredMessage="Privalote įrašyti el. pašto adresą!"/>
                                </h:panelGroup>
                                <h:panelGroup layout="block" class="col-md-3 col-sm-3 col-xs-12">
                                    <b:commandButton value="Pridėti"
                                                     actionListener="#{usersManagementController.addNewUser}"
                                                     update=":usersPage"
                                                     look="success"
                                    />
                                </h:panelGroup>

                            </h:panelGroup>
                        </b:form>
                    </div>
                </div>
            </div>
          </h:panelGroup>
        </div>

    </ui:define>
</ui:composition>